name: continuous

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Set up JDK 17
      uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

    - name: Assemble basic APK
      run: ./gradlew assembleBasicDebug

    - name: Assemble photos APK
      run: ./gradlew assemblePhotosDebug

    - name: Assemble photosonly APK
      run: ./gradlew assemblePhotosonlyDebug

    - name: Upload APKs
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: APKs
        path: app/build/outputs/apk/**/debug/*.apk
        
  fastlane-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      
      - name: Validate fastlane metadata
        uses: ashutoshgngwr/validate-fastlane-supply-metadata@c8857fdbbd3e00f9a5cbe8604bcecfa95ce8fef8 # v2.1.0
